#!/usr/bin/env ruby

require "curb"
require "crack/xml"
require "yaml"
require "addressable/uri"
require "pp"
require "optparse"

CONF = YAML.load_file("etc/ft-poc.yml")

options={}

OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"
  opts.on( "-p", "--phrase PHRASE", String, "Phrase to search for" ) do |phrase|
    options[:phrase] = phrase
  end
  opts.on( "-e", "--extension EXTENSION", String, "Optional extension of the files searched using PHRASE" ) do |ext|
    options[:ext] = ext
  end
end.parse!

if options[:phrase].nil? 
  puts "PHRASE is required"
  exit
end

uri = Addressable::URI.parse(CONF["ft"]["api_url"])
uri.query_values = {
  key: CONF["ft"]["api_key"],
  phrase: options[:phrase],
  extension: ( options[:ext] ? options[:ext] : nil )
}

http = Curl.get(uri.to_s)
# pp Crack::XML.parse(http.body_str)

p uri.to_s



